apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
data:
  default.conf: | # in YAML syntax, | indicates a multi-line string
    server {
      listen 80;
        location / {
          proxy_pass http://flask-app:5001;
        }
    }
---
apiVersion: v1
kind: Service
metadata:
  name: nginx
spec:
  selector:
    app: nginx
  ports: 
  - protocol: TCP
    port: 80
    targetPort: 80
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  labels: 
    app: nginx
spec:
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      volumes:
      - name: nginx-config-volume
        configMap:
          name: nginx-config            # referencing the contents of the ConfigMap
      containers:
      - name: nginx
        image: nginx:alpine
        ports:
        - containerPort: 80
        volumeMounts:
        - name: nginx-config-volume            # referencing the volume name
          mountPath: /etc/nginx/conf.d  # specifying the mount location